# Generated by Django 6.0.6 on 2026-06-08 05:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid7, editable=False, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(db_index=True, default=0)),
                ('name', models.CharField(max_length=100)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='finances.category', verbose_name='parent')),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['position'],
                'abstract': False,
            },
        ),
    ]
