# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 0.1.0
_src_path: /home/kutologojm/PycharmProjects/copier_home/my_copier_templates/backend_templates/django_app_template/
app_name: catalogue
